[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fuzz = { runs = 256 }                                         # the number of fuzz runs for tests
invariant = { runs = 256 }                                    # the number of runs that must execute for each invariant test group
ffi = true                                                   # whether to enable foreign function interface (ffi) cheatcodes or not

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
